version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - '.:/try_rails'
    environment:
      - 'DATABASE_PASSWORD=postgres'
    tty: true
    depends_on:
      - db
    stdin_open: true
    links:
      - db
    
  db:
    image: postgres
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_PASSWORD=postgres'